version: '3.8'
services:
  app:
    build: .
    ports:
      - "3007:3007"
    volumes:
      - app-data:/path/to/data/directory/in/container
    environment:
      - NODE_ENV=development

volumes:
  app-data: